import nltk
from nltk import FreqDist
from nltk.lm import Laplace
import matplotlib.pyplot as plt

nltk.download('punkt')

def calculate_burstiness(text):
    # Tokenize the text into words
    words = nltk.word_tokenize(text)

    # Calculate word frequency distribution
    word_frequency = FreqDist(words)

    # Calculate burstiness using Gini coefficient
    n = len(words)
    gini_coefficient = 1 - sum([(word_frequency[word] / n) ** 2 for word in word_frequency]) / (n ** 2)
    burstiness = 2 * gini_coefficient

    return burstiness

def calculate_perplexity(text):
    # Tokenize the text into words
    words = nltk.word_tokenize(text)

    # Create unigram language model
    unigram_model = Laplace(order=1)
    unigram_model.fit([words], vocabulary_text=words)

    # Calculate perplexity
    perplexity = unigram_model.perplexity(words)

    return perplexity

def is_bot_generated(burstiness, perplexity):
    # Add your heuristic here
    # This is a simple example, you might need to adjust the thresholds based on your observations
    if burstiness > 0.5 and perplexity > 100:
        return True
    else:
        return False

def plot_word_frequency_distribution(text):
    # Tokenize the text into words
    words = nltk.word_tokenize(text)

    # Calculate word frequency distribution
    word_frequency = FreqDist(words)

    # Plot word frequency distribution
    word_frequency.plot(30, cumulative=False)
    plt.show()

def main():
    print("Welcome to the Bot Detection System!")
    user_input = input("Enter the text you want to analyze: ")

    # Calculate and display burstiness
    burstiness = calculate_burstiness(user_input)
    print(f"Burstiness: {burstiness:.2%}")

    # Calculate and display perplexity
    perplexity = calculate_perplexity(user_input)
    print(f"Perplexity: {perplexity:.2f}")

    # Check if the text is likely generated by a bot
    if is_bot_generated(burstiness, perplexity):
        print("The text is likely generated by a bot.")
    else:
        print("The text is likely not generated by a bot.")

    # Plot word frequency distribution
    plot_word_frequency_distribution(user_input)

if __name__ == "__main__":
    main()
